# fly.toml file generated for muddy-sunset-2817 on 2023-02-26T23:01:20Z

app = "muddy-sunset-2817"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  NODE_ENV = "production"
  ETH_CONTRACT_ADDRESS  ="0x07511d92c4a4EbDa057FCE93affcAb9B8e8b5A48"
  ETH_CONTRACT_OWNER = "0xADa95D02B0DAb0d52CCDDa4b9fDFa1a6d068EcF1"
  INFURA_PROJECT_ID = "d054222c82ce4f2995f8e3ee2c514f90"

[experimental]
  auto_rollback = true
  enable_consul = true

[[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[mounts]
  source = "litefs"
  destination = "/var/lib/litefs"
